version: '3.8'

services:
  # 1. Database
  mongodb:
    image: mongo:latest
    container_name: smartera-mongodb
    restart: unless-stopped
    ports:
      - "27037:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Node.js (ETL)
  smartera-etl:
    build: 
      context: ./etl-nodejs/
      #dockerfile: ./etl-nodejs/Dockerfile
    container_name: smartera-etl-sync
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - ./etl-nodejs/ecosystem.config.js:/app/ecosystem.config.js
      - ./etl-nodejs/regions.json:/app/regions.json

  normalize-survey:
    image: engineeringopsilab/normalize-survey-case
    build: 
      context: ./normalize-survey-case
    pull_policy: always
    #network_mode: host
    volumes: 
      - ./normalize-survey-case/surveys-to-ignore.json:/app/surveys-to-ignore.json
    environment:
      MONGO_URI: mongodb://host.docker.internal:22000
      DB_NAME: Minio-Mongo
      COLL_NAME: datapoints

  create-survey:
    image: engineeringopsilab/create-survey
    build: 
      context: .
    pull_policy: always
    #network_mode: host
    volumes: 
      - ./surveys-to-ignore.json:/app/surveys-to-ignore.json
    environment:
      MONGO_URI: mongodb://host.docker.internal:22000
      DB_NAME: Minio-Mongo
      COLL_NAME: datapoints

  osm-init:
    image: engineeringopsilab/osm:latest
    build: ./osm
    pull_policy: always
    #network_mode: host
    environment:
      MONGODB_URI: mongodb://host.docker.internal:22000
      MONGODB_DB_NAME: Minio-Mongo
      MONGODB_COLLECTION_NAME: datapoints
    restart: "no"   


  bih-parser:
    image: engineeringopsilab/bih-py:latest
    build:
      context: ./bih
      dockerfile: Dockerfile    
    pull_policy: always
    #network_mode: host   
    restart: "no"
    volumes:
      - ./smarteraBiH/excel_data:/app/excel_data
    environment:
      MONGODB_URI: mongodb://host.docker.internal:22000
      MONGODB_DB_NAME: Minio-Mongo
      MONGODB_COLLECTION_NAME: datapoints

  analytics:
    image: engineeringopsilab/analytics
    build:
      context: ./analytics
      dockerfile: Dockerfile    
    pull_policy: always
    #network_mode: host   
    restart: "no"
    environment:
      MONGO_URI: mongodb://host.docker.internal:22000
      DB_NAME: Minio-Mongo
      COLLECTION_NAME: datapoints

  NAMA_10R_3NLP:
    image: engineeringopsilab/NAMA_10R_3NLP
    build:
      context: ./NAMA_10R_3NLP
      dockerfile: Dockerfile    
    pull_policy: always
    restart: "no"
    environment:
      ORION_URL: https://dx-lab.eng.it/contextBroker
    command: sh /script.sh

volumes:
  mongo_data: