version: '3.8'

services:

  create-survey:
    image: engineeringopsilab/create-survey
    build: 
      context: .
    pull_policy: always
    #network_mode: host
    volumes: 
      - ./surveys-to-ignore.json:/app/surveys-to-ignore.json
    environment:
      MONGO_URI: mongodb://host.docker.internal:22000
      DB_NAME: Minio-Mongo
      COLL_NAME: datapoints