version: '3.8'

services:

  deduce-dimensions-order:
    image: engineeringopsilab/deduce-dimensions-order
    build:
      context: .
      dockerfile: Dockerfile    
    pull_policy: always
    #network_mode: host   
    restart: "no"
    environment:
      MONGODB_URI: mongodb://host.docker.internal:22000
      DB_NAME: Minio-Mongo
      COLL: datapoints