version: '3.8'

services:

  truncate-last:
    image: engineeringopsilab/truncate-last
    build:
      context: .
      dockerfile: Dockerfile    
    pull_policy: always
    #network_mode: host   
    restart: "no"
    environment:
      MONGODB_URI: mongodb://host.docker.internal:22000
      DB_NAME: Minio-Mongo
      COLL: datapoints
      WORKERS: 6